MODEL:
  NAME: "SEATIZENNET_ae102021only"
  URL: "COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_3x.yaml"
  WEIGHTS : "/home/justine/2022-06-15_LR_0.00025_BATCH_2_ITER_150000_1655286559.4163053/model_final.pth"
  ROI_HEADS:
    NUM_CLASSES: 4
  ANCHOR_GENERATOR:
    SIZES: [[44, 60], [88, 120], [176, 240], [352, 480], [704, 960], [1408, 1920]]
    ASPECT_RATIOS: [[1.0]]
DATASETS:
  TRAIN: ('isa_trainset',)
  TEST: ('isa_valset',)
  EVAL: ('isa_testset',)
DATALOADER:
  NUM_WORKERS: 2
SOLVER:
  IMS_PER_BATCH: 2
  BASE_LR: 0.00025
  STEPS: []
  MAX_ITER: 4000
TEST:
  EVAL_PERIOD: 100