MODEL:
  URL: "COCO-InstanceSegmentation/mask_rcnn_X_101_32x8d_FPN_3x.yaml"
  WEIGHTS : default
  ROI_HEADS:
    NUM_CLASSES: 5
  ANCHOR_GENERATOR:
    SIZES: [[44, 60], [88, 120], [176, 240], [352, 480], [704, 960], [1408, 1920]]
    ASPECT_RATIOS: [[1.0]]
DATALOADER:
  NUM_WORKERS: 16
SOLVER:
  IMS_PER_BATCH: 1
  BASE_LR: 0.00025
  STEPS: []
  MAX_ITER: 13000
TEST:
  EVAL_PERIOD: 250
INPUT:
  MIN_SIZE_TRAIN: 500
  MAX_SIZE_TRAIN: 500
  MIN_SIZE_TEST: 500
  MAX_SIZE_TEST: 500