MODEL:
  URL: "COCO-InstanceSegmentation/mask_rcnn_X_101_32x8d_FPN_3x.yaml"
  ROI_HEADS:
    NUM_CLASSES: 20
  ANCHOR_GENERATOR:
    SIZES: [[44, 60], [88, 120], [176, 240], [352, 480], [704, 960], [1408, 1920]]
    ASPECT_RATIOS: [[1.0]]
DATALOADER:
  NUM_WORKERS: 2
SOLVER:
  IMS_PER_BATCH: 1
  BASE_LR: 0.00025
  STEPS: []
  MAX_ITER: 3000
TEST:
  EVAL_PERIOD: 500
INPUT:
  MIN_SIZE_TRAIN: 1500
  MAX_SIZE_TRAIN: 1500
  MIN_SIZE_TEST: 800
  MAX_SIZE_TEST: 1000
DATA_PATH:
  IMAGES_DIR: '/home/justine/fmr/tiles_1500_overlap25/'  
  COCO_TRAIN: '/home/justine/fmr/tiles_1500_overlap25/coco/coco_train80_species.json'
  COCO_VAL: '/home/justine/fmr/tiles_1500_overlap25/coco/coco_val10_species.json'
  COCO_TEST: '/home/justine/fmr/tiles_1500_overlap25/coco/coco_test10_species.json'
LOGS:
    LOGS_DIR: '/home/justine/fmr/logs/'
    CHECKPOINT: '/home/justine/fmr/logs/20230412_14:23:21x101_allsites_species_overlapping25_tiles1500_ITER3000/model_final.pth'