ae_102021:
  - annotation_path : '/home/justine/fmr/ae_102021/genus_lht_ae1.shp'
  - orthomosaic_path : '/home/justine/fmr/ae_102021/ortho_reprojected.tif'
  - epsg : 32738

ib_102021:
  - annotation_path : '/home/justine/fmr/ib_102021/lht_sp_ib102021.shp'
  - orthomosaic_path : '/home/justine/fmr/ib_102021/ile_blanche_orthomosaic_reprojected.tif'
  - epsg : 32738

su_102021:
  - annotation_path : '/home/justine/fmr/su_102021/lht_genus_38s_surprise2_102021.shp'
  - orthomosaic_path : '/home/justine/fmr/su_102021/su2_orthomosaic_reprojected.tif'
  - epsg : 32738
